# -*- coding: utf-8 -*-
"""Simpl_Quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNesgbCcoiiWaoi9-ysRMum8BA8vgxT6
"""

questions = [
    {
        "question": "What is the capital of France?",
        "choices": ["A) Paris", "B) London", "C) Rome", "D) Berlin"],
        "answer": "A"
    },
    {
        "question": "What is the largest planet in our solar system?",
        "choices": ["A) Earth", "B) Mars", "C) Jupiter", "D) Saturn"],
        "answer": "C"
    },

]

def run_quiz(questions):
    score = 0
    for i, q in enumerate(questions):
        print(f"Q{i+1}: {q['question']}")
        for choice in q['choices']:
            print(choice)
        answer = input("Your answer (A/B/C/D): ").strip().upper()
        if answer == q['answer']:
            print("Correct!\n")
            score += 1
        else:
            print(f"Wrong! The correct answer is {q['answer']}\n")
    print(f"Your final score is {score} out of {len(questions)}")

# Run the quiz
run_quiz(questions)